name: Java CI

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - run: touch starting_10
      - uses: actions/checkout@v3
      - run: touch starting_11
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: touch starting_16
      - name: Build modules
        run: gradle clean build

